services:
  api:
    build:
      context: ./api
    container_name: komite_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - api_storage:/app/storage
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: ./web
      args:
        NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE}
    container_name: komite_web
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - api

  postgres:
    image: postgres:16
    container_name: komite_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: komite_redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
  api_storage:
