from app.api.v1.crud_router_factory import create_crud_router
from app.models.entities import (
    AIPromptTemplate,
    AIRequest,
    AccountingExpense,
    AccountingIncome,
    AccountingIncomeType,
    AccountingPeriod,
    AccountingSupplier,
    AccountingSupplierCategory,
    AccountingSupplierCondominium,
    Attachment,
    AuditLog,
    Bank,
    Building,
    Communication,
    CommunicationRecipient,
    Company,
    CommitteeMember,
    CommonExpenseCharge,
    CommonExpenseChargeItem,
    CommonExpenseRun,
    CommonArea,
    Condominium,
    CondominiumAsset,
    CondominiumInspectionItem,
    CondominiumInspectionTemplate,
    CondominiumOperationalStaff,
    ExternalServiceOrder,
    Incident,
    IncidentEvent,
    Inspection,
    InspectionAnswer,
    InspectionTemplate,
    InspectionTemplateItem,
    InspectionTemplateSection,
    NotificationLog,
    OperationalCalendarException,
    OperationalEventEvidence,
    OperationalEventExecution,
    OperationalRescheduleLog,
    OperationalWorkCalendar,
    PlannedOperationalEvent,
    Report,
    ReportVersion,
    Role,
    SignatureAsset,
    SignaturePermission,
    Task,
    TaskChecklist,
    SupportTicket,
    Unit,
    UnitAnnex,
    UnitContact,
    UnitPet,
    UserCondominium,
)
from app.schemas.entity_schemas import (
    AIPromptTemplateCreate,
    AIPromptTemplateOut,
    AIPromptTemplatePage,
    AIPromptTemplateUpdate,
    AIRequestCreate,
    AIRequestOut,
    AIRequestPage,
    AIRequestUpdate,
    AccountingExpenseCreate,
    AccountingExpenseOut,
    AccountingExpensePage,
    AccountingExpenseUpdate,
    AccountingIncomeCreate,
    AccountingIncomeOut,
    AccountingIncomePage,
    AccountingIncomeTypeCreate,
    AccountingIncomeTypeOut,
    AccountingIncomeTypePage,
    AccountingIncomeTypeUpdate,
    AccountingIncomeUpdate,
    AccountingPeriodCreate,
    AccountingPeriodOut,
    AccountingPeriodPage,
    AccountingPeriodUpdate,
    AccountingSupplierCreate,
    AccountingSupplierCategoryCreate,
    AccountingSupplierCategoryOut,
    AccountingSupplierCategoryPage,
    AccountingSupplierCategoryUpdate,
    AccountingSupplierCondominiumCreate,
    AccountingSupplierCondominiumOut,
    AccountingSupplierCondominiumPage,
    AccountingSupplierCondominiumUpdate,
    AccountingSupplierOut,
    AccountingSupplierPage,
    AccountingSupplierUpdate,
    AttachmentCreate,
    AttachmentOut,
    AttachmentPage,
    AttachmentUpdate,
    AuditLogCreate,
    AuditLogOut,
    AuditLogPage,
    AuditLogUpdate,
    BankCreate,
    BankOut,
    BankPage,
    BankUpdate,
    BuildingCreate,
    BuildingOut,
    BuildingPage,
    BuildingUpdate,
    CommunicationCreate,
    CommunicationOut,
    CommunicationPage,
    CommunicationRecipientCreate,
    CommunicationRecipientOut,
    CommunicationRecipientPage,
    CommunicationRecipientUpdate,
    CommunicationUpdate,
    CompanyCreate,
    CompanyOut,
    CompanyPage,
    CompanyUpdate,
    CommitteeMemberCreate,
    CommitteeMemberOut,
    CommitteeMemberPage,
    CommitteeMemberUpdate,
    CommonExpenseChargeCreate,
    CommonExpenseChargeItemCreate,
    CommonExpenseChargeItemOut,
    CommonExpenseChargeItemPage,
    CommonExpenseChargeItemUpdate,
    CommonExpenseChargeOut,
    CommonExpenseChargePage,
    CommonExpenseChargeUpdate,
    CommonExpenseRunCreate,
    CommonExpenseRunOut,
    CommonExpenseRunPage,
    CommonExpenseRunUpdate,
    CommonAreaCreate,
    CommonAreaOut,
    CommonAreaPage,
    CommonAreaUpdate,
    CondominiumAssetCreate,
    CondominiumAssetOut,
    CondominiumAssetPage,
    CondominiumAssetUpdate,
    CondominiumCreate,
    CondominiumInspectionItemCreate,
    CondominiumInspectionItemOut,
    CondominiumInspectionItemPage,
    CondominiumInspectionItemUpdate,
    CondominiumInspectionTemplateCreate,
    CondominiumInspectionTemplateOut,
    CondominiumInspectionTemplatePage,
    CondominiumInspectionTemplateUpdate,
    CondominiumOperationalStaffCreate,
    CondominiumOperationalStaffOut,
    CondominiumOperationalStaffPage,
    CondominiumOperationalStaffUpdate,
    CondominiumOut,
    CondominiumPage,
    CondominiumUpdate,
    ExternalServiceOrderCreate,
    ExternalServiceOrderOut,
    ExternalServiceOrderPage,
    ExternalServiceOrderUpdate,
    IncidentCreate,
    IncidentEventCreate,
    IncidentEventOut,
    IncidentEventPage,
    IncidentEventUpdate,
    IncidentOut,
    IncidentPage,
    IncidentUpdate,
    InspectionAnswerCreate,
    InspectionAnswerOut,
    InspectionAnswerPage,
    InspectionAnswerUpdate,
    InspectionCreate,
    InspectionOut,
    InspectionPage,
    InspectionTemplateCreate,
    InspectionTemplateItemCreate,
    InspectionTemplateItemOut,
    InspectionTemplateItemPage,
    InspectionTemplateItemUpdate,
    InspectionTemplateOut,
    InspectionTemplatePage,
    InspectionTemplateSectionCreate,
    InspectionTemplateSectionOut,
    InspectionTemplateSectionPage,
    InspectionTemplateSectionUpdate,
    InspectionTemplateUpdate,
    InspectionUpdate,
    NotificationLogCreate,
    NotificationLogOut,
    NotificationLogPage,
    NotificationLogUpdate,
    OperationalCalendarExceptionCreate,
    OperationalCalendarExceptionOut,
    OperationalCalendarExceptionPage,
    OperationalCalendarExceptionUpdate,
    OperationalEventEvidenceCreate,
    OperationalEventEvidenceOut,
    OperationalEventEvidencePage,
    OperationalEventEvidenceUpdate,
    OperationalEventExecutionCreate,
    OperationalEventExecutionOut,
    OperationalEventExecutionPage,
    OperationalEventExecutionUpdate,
    OperationalRescheduleLogCreate,
    OperationalRescheduleLogOut,
    OperationalRescheduleLogPage,
    OperationalRescheduleLogUpdate,
    OperationalWorkCalendarCreate,
    OperationalWorkCalendarOut,
    OperationalWorkCalendarPage,
    OperationalWorkCalendarUpdate,
    PlannedOperationalEventCreate,
    PlannedOperationalEventOut,
    PlannedOperationalEventPage,
    PlannedOperationalEventUpdate,
    ReportCreate,
    ReportOut,
    ReportPage,
    ReportUpdate,
    ReportVersionCreate,
    ReportVersionOut,
    ReportVersionPage,
    ReportVersionUpdate,
    RoleCreate,
    RoleOut,
    RolePage,
    RoleUpdate,
    SignatureAssetCreate,
    SignatureAssetOut,
    SignatureAssetPage,
    SignatureAssetUpdate,
    SignaturePermissionCreate,
    SignaturePermissionOut,
    SignaturePermissionPage,
    SignaturePermissionUpdate,
    TaskChecklistCreate,
    TaskChecklistOut,
    TaskChecklistPage,
    TaskChecklistUpdate,
    TaskCreate,
    TaskOut,
    TaskPage,
    TaskUpdate,
    SupportTicketCreate,
    SupportTicketOut,
    SupportTicketPage,
    SupportTicketUpdate,
    UnitAnnexCreate,
    UnitAnnexOut,
    UnitAnnexPage,
    UnitAnnexUpdate,
    UnitCreate,
    UnitContactCreate,
    UnitContactOut,
    UnitContactPage,
    UnitContactUpdate,
    UnitOut,
    UnitPage,
    UnitPetCreate,
    UnitPetOut,
    UnitPetPage,
    UnitPetUpdate,
    UnitUpdate,
    UserCondominiumCreate,
    UserCondominiumOut,
    UserCondominiumPage,
    UserCondominiumUpdate,
)

entity_routers = [
    create_crud_router(model=Company, prefix="/api/v1/companies", tag="Companies", create_schema=CompanyCreate, update_schema=CompanyUpdate, response_schema=CompanyOut, page_schema=CompanyPage, search_fields=("name", "rut")),
    create_crud_router(model=Bank, prefix="/api/v1/banks", tag="Banks", create_schema=BankCreate, update_schema=BankUpdate, response_schema=BankOut, page_schema=BankPage, search_fields=("name", "code", "country")),
    create_crud_router(model=Condominium, prefix="/api/v1/condominiums", tag="Condominiums", create_schema=CondominiumCreate, update_schema=CondominiumUpdate, response_schema=CondominiumOut, page_schema=CondominiumPage, search_fields=("name", "address")),
    create_crud_router(model=CondominiumOperationalStaff, prefix="/api/v1/condominium-operational-staff", tag="Condominium operational staff", create_schema=CondominiumOperationalStaffCreate, update_schema=CondominiumOperationalStaffUpdate, response_schema=CondominiumOperationalStaffOut, page_schema=CondominiumOperationalStaffPage, search_fields=("portal_profile", "responsibility", "notes")),
    create_crud_router(model=Building, prefix="/api/v1/buildings", tag="Buildings", create_schema=BuildingCreate, update_schema=BuildingUpdate, response_schema=BuildingOut, page_schema=BuildingPage, search_fields=("name",)),
    create_crud_router(model=CommonArea, prefix="/api/v1/common-areas", tag="Common areas", create_schema=CommonAreaCreate, update_schema=CommonAreaUpdate, response_schema=CommonAreaOut, page_schema=CommonAreaPage, search_fields=("name", "area_type", "location", "notes"), write_requires_komite=False),
    create_crud_router(model=CondominiumAsset, prefix="/api/v1/condominium-assets", tag="Condominium assets", create_schema=CondominiumAssetCreate, update_schema=CondominiumAssetUpdate, response_schema=CondominiumAssetOut, page_schema=CondominiumAssetPage, search_fields=("name", "asset_type", "location", "brand", "model", "serial_number", "provider", "notes"), write_requires_komite=False),
    create_crud_router(model=Unit, prefix="/api/v1/units", tag="Units", create_schema=UnitCreate, update_schema=UnitUpdate, response_schema=UnitOut, page_schema=UnitPage, search_fields=("identifier",), write_requires_komite=False),
    create_crud_router(model=UnitAnnex, prefix="/api/v1/unit-annexes", tag="Unit annexes", create_schema=UnitAnnexCreate, update_schema=UnitAnnexUpdate, response_schema=UnitAnnexOut, page_schema=UnitAnnexPage, search_fields=("identifier", "description", "annex_type"), write_requires_komite=False),
    create_crud_router(model=UnitContact, prefix="/api/v1/unit-contacts", tag="Unit contacts", create_schema=UnitContactCreate, update_schema=UnitContactUpdate, response_schema=UnitContactOut, page_schema=UnitContactPage, search_fields=("full_name", "email", "phone", "document_number", "relationship_type"), write_requires_komite=False),
    create_crud_router(model=UnitPet, prefix="/api/v1/unit-pets", tag="Unit pets", create_schema=UnitPetCreate, update_schema=UnitPetUpdate, response_schema=UnitPetOut, page_schema=UnitPetPage, search_fields=("name", "species", "breed", "chip_number"), write_requires_komite=False),
    create_crud_router(model=SignatureAsset, prefix="/api/v1/signature-assets", tag="Signature assets", create_schema=SignatureAssetCreate, update_schema=SignatureAssetUpdate, response_schema=SignatureAssetOut, page_schema=SignatureAssetPage, search_fields=("name", "signer_name", "signer_document", "signer_position")),
    create_crud_router(model=SignaturePermission, prefix="/api/v1/signature-permissions", tag="Signature permissions", create_schema=SignaturePermissionCreate, update_schema=SignaturePermissionUpdate, response_schema=SignaturePermissionOut, page_schema=SignaturePermissionPage),
    create_crud_router(model=CommitteeMember, prefix="/api/v1/committee-members", tag="Committee members", create_schema=CommitteeMemberCreate, update_schema=CommitteeMemberUpdate, response_schema=CommitteeMemberOut, page_schema=CommitteeMemberPage, search_fields=("full_name", "email", "phone", "position"), write_requires_komite=False),
    create_crud_router(model=Role, prefix="/api/v1/roles", tag="Roles", create_schema=RoleCreate, update_schema=RoleUpdate, response_schema=RoleOut, page_schema=RolePage, search_fields=("code", "name")),
    create_crud_router(model=UserCondominium, prefix="/api/v1/user-condominiums", tag="User condominiums", create_schema=UserCondominiumCreate, update_schema=UserCondominiumUpdate, response_schema=UserCondominiumOut, page_schema=UserCondominiumPage),
    create_crud_router(model=Incident, prefix="/api/v1/incidents", tag="Incidents", create_schema=IncidentCreate, update_schema=IncidentUpdate, response_schema=IncidentOut, page_schema=IncidentPage, search_fields=("category", "original_description", "ai_description")),
    create_crud_router(model=IncidentEvent, prefix="/api/v1/incident-events", tag="Incident events", create_schema=IncidentEventCreate, update_schema=IncidentEventUpdate, response_schema=IncidentEventOut, page_schema=IncidentEventPage, search_fields=("event_type", "comment")),
    create_crud_router(model=Task, prefix="/api/v1/tasks", tag="Tasks", create_schema=TaskCreate, update_schema=TaskUpdate, response_schema=TaskOut, page_schema=TaskPage, search_fields=("title", "description")),
    create_crud_router(model=SupportTicket, prefix="/api/v1/support-tickets", tag="Support tickets", create_schema=SupportTicketCreate, update_schema=SupportTicketUpdate, response_schema=SupportTicketOut, page_schema=SupportTicketPage, search_fields=("subject", "description", "requester_email", "category")),
    create_crud_router(model=TaskChecklist, prefix="/api/v1/task-checklists", tag="Task checklists", create_schema=TaskChecklistCreate, update_schema=TaskChecklistUpdate, response_schema=TaskChecklistOut, page_schema=TaskChecklistPage, search_fields=("label",)),
    create_crud_router(model=InspectionTemplate, prefix="/api/v1/inspection-templates", tag="Inspection templates", create_schema=InspectionTemplateCreate, update_schema=InspectionTemplateUpdate, response_schema=InspectionTemplateOut, page_schema=InspectionTemplatePage, search_fields=("name", "inspection_type")),
    create_crud_router(model=InspectionTemplateSection, prefix="/api/v1/inspection-template-sections", tag="Inspection template sections", create_schema=InspectionTemplateSectionCreate, update_schema=InspectionTemplateSectionUpdate, response_schema=InspectionTemplateSectionOut, page_schema=InspectionTemplateSectionPage, search_fields=("name", "description")),
    create_crud_router(model=InspectionTemplateItem, prefix="/api/v1/inspection-template-items", tag="Inspection template items", create_schema=InspectionTemplateItemCreate, update_schema=InspectionTemplateItemUpdate, response_schema=InspectionTemplateItemOut, page_schema=InspectionTemplateItemPage, search_fields=("asset_name", "task_name", "instructions", "periodicity")),
    create_crud_router(model=CondominiumInspectionTemplate, prefix="/api/v1/condominium-inspection-templates", tag="Condominium inspection templates", create_schema=CondominiumInspectionTemplateCreate, update_schema=CondominiumInspectionTemplateUpdate, response_schema=CondominiumInspectionTemplateOut, page_schema=CondominiumInspectionTemplatePage, search_fields=("name",), write_requires_komite=False),
    create_crud_router(model=CondominiumInspectionItem, prefix="/api/v1/condominium-inspection-items", tag="Condominium inspection items", create_schema=CondominiumInspectionItemCreate, update_schema=CondominiumInspectionItemUpdate, response_schema=CondominiumInspectionItemOut, page_schema=CondominiumInspectionItemPage, search_fields=("section_name", "asset_name", "task_name", "instructions", "periodicity"), write_requires_komite=False),
    create_crud_router(model=OperationalWorkCalendar, prefix="/api/v1/operational-work-calendars", tag="Operational work calendars", create_schema=OperationalWorkCalendarCreate, update_schema=OperationalWorkCalendarUpdate, response_schema=OperationalWorkCalendarOut, page_schema=OperationalWorkCalendarPage, search_fields=("name", "calendar_type"), write_requires_komite=False),
    create_crud_router(model=OperationalCalendarException, prefix="/api/v1/operational-calendar-exceptions", tag="Operational calendar exceptions", create_schema=OperationalCalendarExceptionCreate, update_schema=OperationalCalendarExceptionUpdate, response_schema=OperationalCalendarExceptionOut, page_schema=OperationalCalendarExceptionPage, search_fields=("exception_type", "reason", "source"), write_requires_komite=False),
    create_crud_router(model=PlannedOperationalEvent, prefix="/api/v1/planned-operational-events", tag="Planned operational events", create_schema=PlannedOperationalEventCreate, update_schema=PlannedOperationalEventUpdate, response_schema=PlannedOperationalEventOut, page_schema=PlannedOperationalEventPage, search_fields=("title", "description", "assigned_profile", "event_type", "source_type"), write_requires_komite=False),
    create_crud_router(model=OperationalEventExecution, prefix="/api/v1/operational-event-executions", tag="Operational event executions", create_schema=OperationalEventExecutionCreate, update_schema=OperationalEventExecutionUpdate, response_schema=OperationalEventExecutionOut, page_schema=OperationalEventExecutionPage, search_fields=("result", "comments", "validation_status"), write_requires_komite=False),
    create_crud_router(model=OperationalEventEvidence, prefix="/api/v1/operational-event-evidence", tag="Operational event evidence", create_schema=OperationalEventEvidenceCreate, update_schema=OperationalEventEvidenceUpdate, response_schema=OperationalEventEvidenceOut, page_schema=OperationalEventEvidencePage, search_fields=("evidence_type", "description"), write_requires_komite=False),
    create_crud_router(model=OperationalRescheduleLog, prefix="/api/v1/operational-reschedule-logs", tag="Operational reschedule logs", create_schema=OperationalRescheduleLogCreate, update_schema=OperationalRescheduleLogUpdate, response_schema=OperationalRescheduleLogOut, page_schema=OperationalRescheduleLogPage, search_fields=("reason",), write_requires_komite=False),
    create_crud_router(model=Inspection, prefix="/api/v1/inspections", tag="Inspections", create_schema=InspectionCreate, update_schema=InspectionUpdate, response_schema=InspectionOut, page_schema=InspectionPage, search_fields=("inspection_type", "observations")),
    create_crud_router(model=InspectionAnswer, prefix="/api/v1/inspection-answers", tag="Inspection answers", create_schema=InspectionAnswerCreate, update_schema=InspectionAnswerUpdate, response_schema=InspectionAnswerOut, page_schema=InspectionAnswerPage, search_fields=("question_key", "question_label")),
    create_crud_router(model=Report, prefix="/api/v1/reports", tag="Reports", create_schema=ReportCreate, update_schema=ReportUpdate, response_schema=ReportOut, page_schema=ReportPage, search_fields=("title", "report_type")),
    create_crud_router(model=ReportVersion, prefix="/api/v1/report-versions", tag="Report versions", create_schema=ReportVersionCreate, update_schema=ReportVersionUpdate, response_schema=ReportVersionOut, page_schema=ReportVersionPage, search_fields=("source", "notes")),
    create_crud_router(model=Communication, prefix="/api/v1/communications", tag="Communications", create_schema=CommunicationCreate, update_schema=CommunicationUpdate, response_schema=CommunicationOut, page_schema=CommunicationPage, search_fields=("title", "body", "communication_type")),
    create_crud_router(model=CommunicationRecipient, prefix="/api/v1/communication-recipients", tag="Communication recipients", create_schema=CommunicationRecipientCreate, update_schema=CommunicationRecipientUpdate, response_schema=CommunicationRecipientOut, page_schema=CommunicationRecipientPage, search_fields=("channel", "destination")),
    create_crud_router(model=AccountingPeriod, prefix="/api/v1/accounting-periods", tag="Accounting periods", create_schema=AccountingPeriodCreate, update_schema=AccountingPeriodUpdate, response_schema=AccountingPeriodOut, page_schema=AccountingPeriodPage, search_fields=("name", "description", "status"), write_requires_komite=False),
    create_crud_router(model=AccountingSupplierCategory, prefix="/api/v1/accounting-supplier-categories", tag="Accounting supplier categories", create_schema=AccountingSupplierCategoryCreate, update_schema=AccountingSupplierCategoryUpdate, response_schema=AccountingSupplierCategoryOut, page_schema=AccountingSupplierCategoryPage, search_fields=("name", "code"), write_requires_komite=False),
    create_crud_router(model=AccountingSupplier, prefix="/api/v1/accounting-suppliers", tag="Accounting suppliers", create_schema=AccountingSupplierCreate, update_schema=AccountingSupplierUpdate, response_schema=AccountingSupplierOut, page_schema=AccountingSupplierPage, search_fields=("name", "rut", "category"), write_requires_komite=False),
    create_crud_router(model=AccountingSupplierCondominium, prefix="/api/v1/accounting-supplier-condominiums", tag="Accounting supplier condominiums", create_schema=AccountingSupplierCondominiumCreate, update_schema=AccountingSupplierCondominiumUpdate, response_schema=AccountingSupplierCondominiumOut, page_schema=AccountingSupplierCondominiumPage, search_fields=("notes",), write_requires_komite=False),
    create_crud_router(model=AccountingIncomeType, prefix="/api/v1/accounting-income-types", tag="Accounting income types", create_schema=AccountingIncomeTypeCreate, update_schema=AccountingIncomeTypeUpdate, response_schema=AccountingIncomeTypeOut, page_schema=AccountingIncomeTypePage, search_fields=("name", "code"), write_requires_komite=False),
    create_crud_router(model=AccountingIncome, prefix="/api/v1/accounting-incomes", tag="Accounting incomes", create_schema=AccountingIncomeCreate, update_schema=AccountingIncomeUpdate, response_schema=AccountingIncomeOut, page_schema=AccountingIncomePage, search_fields=("description", "payment_method", "reference", "status"), write_requires_komite=False),
    create_crud_router(model=AccountingExpense, prefix="/api/v1/accounting-expenses", tag="Accounting expenses", create_schema=AccountingExpenseCreate, update_schema=AccountingExpenseUpdate, response_schema=AccountingExpenseOut, page_schema=AccountingExpensePage, search_fields=("description", "category", "document_number", "status"), write_requires_komite=False),
    create_crud_router(model=CommonExpenseRun, prefix="/api/v1/common-expense-runs", tag="Common expense runs", create_schema=CommonExpenseRunCreate, update_schema=CommonExpenseRunUpdate, response_schema=CommonExpenseRunOut, page_schema=CommonExpenseRunPage, search_fields=("status",), write_requires_komite=False),
    create_crud_router(model=CommonExpenseCharge, prefix="/api/v1/common-expense-charges", tag="Common expense charges", create_schema=CommonExpenseChargeCreate, update_schema=CommonExpenseChargeUpdate, response_schema=CommonExpenseChargeOut, page_schema=CommonExpenseChargePage, search_fields=("status",), write_requires_komite=False),
    create_crud_router(model=CommonExpenseChargeItem, prefix="/api/v1/common-expense-charge-items", tag="Common expense charge items", create_schema=CommonExpenseChargeItemCreate, update_schema=CommonExpenseChargeItemUpdate, response_schema=CommonExpenseChargeItemOut, page_schema=CommonExpenseChargeItemPage, search_fields=("description",), write_requires_komite=False),
    create_crud_router(model=Attachment, prefix="/api/v1/attachments", tag="Attachments", create_schema=AttachmentCreate, update_schema=AttachmentUpdate, response_schema=AttachmentOut, page_schema=AttachmentPage, search_fields=("file_name", "file_type", "mime_type")),
    create_crud_router(model=AuditLog, prefix="/api/v1/audit-logs", tag="Audit logs", create_schema=AuditLogCreate, update_schema=AuditLogUpdate, response_schema=AuditLogOut, page_schema=AuditLogPage, search_fields=("action", "entity_type")),
    create_crud_router(model=AIPromptTemplate, prefix="/api/v1/ai-prompt-templates", tag="AI prompt templates", create_schema=AIPromptTemplateCreate, update_schema=AIPromptTemplateUpdate, response_schema=AIPromptTemplateOut, page_schema=AIPromptTemplatePage, search_fields=("key", "name", "purpose", "module", "asset_type")),
    create_crud_router(model=AIRequest, prefix="/api/v1/ai-requests", tag="AI requests", create_schema=AIRequestCreate, update_schema=AIRequestUpdate, response_schema=AIRequestOut, page_schema=AIRequestPage, search_fields=("provider", "model", "purpose")),
    create_crud_router(model=ExternalServiceOrder, prefix="/api/v1/external-service-orders", tag="External service orders", create_schema=ExternalServiceOrderCreate, update_schema=ExternalServiceOrderUpdate, response_schema=ExternalServiceOrderOut, page_schema=ExternalServiceOrderPage, search_fields=("title", "provider_name", "provider_email", "status", "prompt_key"), write_requires_komite=False),
    create_crud_router(model=NotificationLog, prefix="/api/v1/notification-logs", tag="Notification logs", create_schema=NotificationLogCreate, update_schema=NotificationLogUpdate, response_schema=NotificationLogOut, page_schema=NotificationLogPage, search_fields=("channel", "destination", "status")),
]
