from app.api.v1.crud_router_factory import create_crud_router
from app.models.entities import (
    AIRequest,
    Attachment,
    AuditLog,
    Bank,
    Building,
    Communication,
    CommunicationRecipient,
    Company,
    CommitteeMember,
    Condominium,
    CondominiumOperationalStaff,
    Incident,
    IncidentEvent,
    Inspection,
    InspectionAnswer,
    InspectionTemplate,
    NotificationLog,
    Report,
    ReportVersion,
    Role,
    Task,
    TaskChecklist,
    SupportTicket,
    Unit,
    UnitContact,
    UserCondominium,
)
from app.schemas.entity_schemas import (
    AIRequestCreate,
    AIRequestOut,
    AIRequestPage,
    AIRequestUpdate,
    AttachmentCreate,
    AttachmentOut,
    AttachmentPage,
    AttachmentUpdate,
    AuditLogCreate,
    AuditLogOut,
    AuditLogPage,
    AuditLogUpdate,
    BankCreate,
    BankOut,
    BankPage,
    BankUpdate,
    BuildingCreate,
    BuildingOut,
    BuildingPage,
    BuildingUpdate,
    CommunicationCreate,
    CommunicationOut,
    CommunicationPage,
    CommunicationRecipientCreate,
    CommunicationRecipientOut,
    CommunicationRecipientPage,
    CommunicationRecipientUpdate,
    CommunicationUpdate,
    CompanyCreate,
    CompanyOut,
    CompanyPage,
    CompanyUpdate,
    CommitteeMemberCreate,
    CommitteeMemberOut,
    CommitteeMemberPage,
    CommitteeMemberUpdate,
    CondominiumCreate,
    CondominiumOperationalStaffCreate,
    CondominiumOperationalStaffOut,
    CondominiumOperationalStaffPage,
    CondominiumOperationalStaffUpdate,
    CondominiumOut,
    CondominiumPage,
    CondominiumUpdate,
    IncidentCreate,
    IncidentEventCreate,
    IncidentEventOut,
    IncidentEventPage,
    IncidentEventUpdate,
    IncidentOut,
    IncidentPage,
    IncidentUpdate,
    InspectionAnswerCreate,
    InspectionAnswerOut,
    InspectionAnswerPage,
    InspectionAnswerUpdate,
    InspectionCreate,
    InspectionOut,
    InspectionPage,
    InspectionTemplateCreate,
    InspectionTemplateOut,
    InspectionTemplatePage,
    InspectionTemplateUpdate,
    InspectionUpdate,
    NotificationLogCreate,
    NotificationLogOut,
    NotificationLogPage,
    NotificationLogUpdate,
    ReportCreate,
    ReportOut,
    ReportPage,
    ReportUpdate,
    ReportVersionCreate,
    ReportVersionOut,
    ReportVersionPage,
    ReportVersionUpdate,
    RoleCreate,
    RoleOut,
    RolePage,
    RoleUpdate,
    TaskChecklistCreate,
    TaskChecklistOut,
    TaskChecklistPage,
    TaskChecklistUpdate,
    TaskCreate,
    TaskOut,
    TaskPage,
    TaskUpdate,
    SupportTicketCreate,
    SupportTicketOut,
    SupportTicketPage,
    SupportTicketUpdate,
    UnitCreate,
    UnitContactCreate,
    UnitContactOut,
    UnitContactPage,
    UnitContactUpdate,
    UnitOut,
    UnitPage,
    UnitUpdate,
    UserCondominiumCreate,
    UserCondominiumOut,
    UserCondominiumPage,
    UserCondominiumUpdate,
)

entity_routers = [
    create_crud_router(model=Company, prefix="/api/v1/companies", tag="Companies", create_schema=CompanyCreate, update_schema=CompanyUpdate, response_schema=CompanyOut, page_schema=CompanyPage, search_fields=("name", "rut")),
    create_crud_router(model=Bank, prefix="/api/v1/banks", tag="Banks", create_schema=BankCreate, update_schema=BankUpdate, response_schema=BankOut, page_schema=BankPage, search_fields=("name", "code", "country")),
    create_crud_router(model=Condominium, prefix="/api/v1/condominiums", tag="Condominiums", create_schema=CondominiumCreate, update_schema=CondominiumUpdate, response_schema=CondominiumOut, page_schema=CondominiumPage, search_fields=("name", "address")),
    create_crud_router(model=CondominiumOperationalStaff, prefix="/api/v1/condominium-operational-staff", tag="Condominium operational staff", create_schema=CondominiumOperationalStaffCreate, update_schema=CondominiumOperationalStaffUpdate, response_schema=CondominiumOperationalStaffOut, page_schema=CondominiumOperationalStaffPage, search_fields=("portal_profile", "responsibility", "notes")),
    create_crud_router(model=Building, prefix="/api/v1/buildings", tag="Buildings", create_schema=BuildingCreate, update_schema=BuildingUpdate, response_schema=BuildingOut, page_schema=BuildingPage, search_fields=("name",)),
    create_crud_router(model=Unit, prefix="/api/v1/units", tag="Units", create_schema=UnitCreate, update_schema=UnitUpdate, response_schema=UnitOut, page_schema=UnitPage, search_fields=("identifier",), write_requires_komite=False),
    create_crud_router(model=UnitContact, prefix="/api/v1/unit-contacts", tag="Unit contacts", create_schema=UnitContactCreate, update_schema=UnitContactUpdate, response_schema=UnitContactOut, page_schema=UnitContactPage, search_fields=("full_name", "email", "phone", "document_number", "relationship_type"), write_requires_komite=False),
    create_crud_router(model=CommitteeMember, prefix="/api/v1/committee-members", tag="Committee members", create_schema=CommitteeMemberCreate, update_schema=CommitteeMemberUpdate, response_schema=CommitteeMemberOut, page_schema=CommitteeMemberPage, search_fields=("full_name", "email", "phone", "position"), write_requires_komite=False),
    create_crud_router(model=Role, prefix="/api/v1/roles", tag="Roles", create_schema=RoleCreate, update_schema=RoleUpdate, response_schema=RoleOut, page_schema=RolePage, search_fields=("code", "name")),
    create_crud_router(model=UserCondominium, prefix="/api/v1/user-condominiums", tag="User condominiums", create_schema=UserCondominiumCreate, update_schema=UserCondominiumUpdate, response_schema=UserCondominiumOut, page_schema=UserCondominiumPage),
    create_crud_router(model=Incident, prefix="/api/v1/incidents", tag="Incidents", create_schema=IncidentCreate, update_schema=IncidentUpdate, response_schema=IncidentOut, page_schema=IncidentPage, search_fields=("category", "original_description", "ai_description")),
    create_crud_router(model=IncidentEvent, prefix="/api/v1/incident-events", tag="Incident events", create_schema=IncidentEventCreate, update_schema=IncidentEventUpdate, response_schema=IncidentEventOut, page_schema=IncidentEventPage, search_fields=("event_type", "comment")),
    create_crud_router(model=Task, prefix="/api/v1/tasks", tag="Tasks", create_schema=TaskCreate, update_schema=TaskUpdate, response_schema=TaskOut, page_schema=TaskPage, search_fields=("title", "description")),
    create_crud_router(model=SupportTicket, prefix="/api/v1/support-tickets", tag="Support tickets", create_schema=SupportTicketCreate, update_schema=SupportTicketUpdate, response_schema=SupportTicketOut, page_schema=SupportTicketPage, search_fields=("subject", "description", "requester_email", "category")),
    create_crud_router(model=TaskChecklist, prefix="/api/v1/task-checklists", tag="Task checklists", create_schema=TaskChecklistCreate, update_schema=TaskChecklistUpdate, response_schema=TaskChecklistOut, page_schema=TaskChecklistPage, search_fields=("label",)),
    create_crud_router(model=InspectionTemplate, prefix="/api/v1/inspection-templates", tag="Inspection templates", create_schema=InspectionTemplateCreate, update_schema=InspectionTemplateUpdate, response_schema=InspectionTemplateOut, page_schema=InspectionTemplatePage, search_fields=("name", "inspection_type")),
    create_crud_router(model=Inspection, prefix="/api/v1/inspections", tag="Inspections", create_schema=InspectionCreate, update_schema=InspectionUpdate, response_schema=InspectionOut, page_schema=InspectionPage, search_fields=("inspection_type", "observations")),
    create_crud_router(model=InspectionAnswer, prefix="/api/v1/inspection-answers", tag="Inspection answers", create_schema=InspectionAnswerCreate, update_schema=InspectionAnswerUpdate, response_schema=InspectionAnswerOut, page_schema=InspectionAnswerPage, search_fields=("question_key", "question_label")),
    create_crud_router(model=Report, prefix="/api/v1/reports", tag="Reports", create_schema=ReportCreate, update_schema=ReportUpdate, response_schema=ReportOut, page_schema=ReportPage, search_fields=("title", "report_type")),
    create_crud_router(model=ReportVersion, prefix="/api/v1/report-versions", tag="Report versions", create_schema=ReportVersionCreate, update_schema=ReportVersionUpdate, response_schema=ReportVersionOut, page_schema=ReportVersionPage, search_fields=("source", "notes")),
    create_crud_router(model=Communication, prefix="/api/v1/communications", tag="Communications", create_schema=CommunicationCreate, update_schema=CommunicationUpdate, response_schema=CommunicationOut, page_schema=CommunicationPage, search_fields=("title", "body", "communication_type")),
    create_crud_router(model=CommunicationRecipient, prefix="/api/v1/communication-recipients", tag="Communication recipients", create_schema=CommunicationRecipientCreate, update_schema=CommunicationRecipientUpdate, response_schema=CommunicationRecipientOut, page_schema=CommunicationRecipientPage, search_fields=("channel", "destination")),
    create_crud_router(model=Attachment, prefix="/api/v1/attachments", tag="Attachments", create_schema=AttachmentCreate, update_schema=AttachmentUpdate, response_schema=AttachmentOut, page_schema=AttachmentPage, search_fields=("file_name", "file_type", "mime_type")),
    create_crud_router(model=AuditLog, prefix="/api/v1/audit-logs", tag="Audit logs", create_schema=AuditLogCreate, update_schema=AuditLogUpdate, response_schema=AuditLogOut, page_schema=AuditLogPage, search_fields=("action", "entity_type")),
    create_crud_router(model=AIRequest, prefix="/api/v1/ai-requests", tag="AI requests", create_schema=AIRequestCreate, update_schema=AIRequestUpdate, response_schema=AIRequestOut, page_schema=AIRequestPage, search_fields=("provider", "model", "purpose")),
    create_crud_router(model=NotificationLog, prefix="/api/v1/notification-logs", tag="Notification logs", create_schema=NotificationLogCreate, update_schema=NotificationLogUpdate, response_schema=NotificationLogOut, page_schema=NotificationLogPage, search_fields=("channel", "destination", "status")),
]
